# Generated by Django 2.2.1 on 2019-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_pic',
            field=models.ImageField(upload_to='image/product'),
        ),
    ]
