# Generated by Django 2.2.1 on 2019-10-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20191005_0509'),
    ]

    operations = [
    ]
