# Generated by Django 2.2.1 on 2019-10-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191006_1929'),
    ]

    operations = [
    ]
