# Generated by Django 2.2.1 on 2019-10-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191006_2136'),
    ]

    operations = [
    ]
