# Generated by Django 2.2.1 on 2019-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191006_2212'),
    ]

    operations = [
    ]
