# Generated by Django 2.2.1 on 2019-10-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20191006_2221'),
    ]

    operations = [
    ]
