# Generated by Django 2.2.1 on 2019-10-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20191007_1200'),
    ]

    operations = [
    ]
