# Generated by Django 2.2.1 on 2019-10-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20191009_1208'),
    ]

    operations = [
    ]
