# Generated by Django 2.2.1 on 2019-10-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20191009_1224'),
    ]

    operations = [
    ]
