# Generated by Django 2.2.1 on 2019-10-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_product_origprice'),
    ]

    operations = [
    ]
