# Generated by Django 2.2.1 on 2019-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20191225_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='stud_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='stud_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_name',
        ),
        migrations.AddField(
            model_name='student',
            name='stud_age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
