# Generated by Django 2.2.1 on 2019-12-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20191225_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
