# Generated by Django 2.2 on 2019-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articles_bsell_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('phone', models.CharField(max_length=250)),
                ('upline', models.CharField(max_length=250)),
                ('tin', models.CharField(max_length=250)),
                ('points', models.FloatField(blank=True, default=0.0, null=True)),
                ('money', models.FloatField(blank=True, default=0.0, null=True)),
                ('photo', models.ImageField(default='avatars/default/default.jpg', upload_to='avatar')),
            ],
        ),
    ]
