# Generated by Django 2.2.1 on 2019-09-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=250)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('markup', models.FloatField(blank=True, default=0.0, null=True)),
                ('referal', models.FloatField(blank=True, default=0.0, null=True)),
                ('model_pic', models.ImageField(upload_to='prod_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=250)),
                ('stud_age', models.IntegerField(blank=True, default=18, null=True)),
                ('stud_phone', models.CharField(max_length=250)),
            ],
        ),
    ]
