# Generated by Django 2.2.1 on 2019-10-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191005_0517'),
    ]

    operations = [
    ]
