# Generated by Django 2.2.1 on 2019-10-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191005_0520'),
    ]

    operations = [
    ]
