# Generated by Django 2.2.1 on 2019-10-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191006_1250'),
    ]

    operations = [
    ]
