# Generated by Django 2.2.1 on 2019-10-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191006_1731'),
    ]

    operations = [
    ]
