# Generated by Django 2.2.1 on 2019-10-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20191006_2221'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
