# Generated by Django 2.2.1 on 2019-10-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20191008_1218'),
    ]

    operations = [
    ]
