# Generated by Django 2.2.1 on 2019-10-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20191009_1519'),
    ]

    operations = [
    ]
